 apply plugin: 'com.android.application'

android {
    compileSdkVersion 31

    defaultConfig {
        applicationId "xyz.monkeytong.hongbao"
        minSdkVersion 21
        targetSdkVersion 31
        versionCode 8000002
        versionName "v8.0.2"
    }

    signingConfigs {
        release {
            keyAlias 'WeChatLuckyMoney'
            keyPassword 'WeChatLuckyMoney'
            storeFile file('../WeChatLuckyMoney.jks')
            storePassword 'WeChatLuckyMoney'
        }
    }

    buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.release
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
}

 dependencies {
     implementation fileTree(include: ['*.jar'], dir: 'libs')
     implementation "androidx.localbroadcastmanager:localbroadcastmanager:1.1.0"
     implementation 'androidx.appcompat:appcompat:1.4.1'
     implementation 'androidx.preference:preference:1.1.1'
     implementation("com.squareup.okhttp3:okhttp:4.9.3")
 }