 apply plugin: 'com.android.application'

android {
    compileSdkVersion 31

    defaultConfig {
        applicationId "xyz.monkeytong.hongbao"
        minSdkVersion 21
        targetSdkVersion 31
        versionCode 8000000
        versionName "v8.0.0"
    }

    signingConfigs {
//        release {
//            keyAlias 'key'
//            keyPassword 'wxj19931028'
//            storeFile file('D:/project/demo/key.jks')
//            storePassword 'wxj19931028'
//        }
    }

    buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
//            signingConfig signingConfigs.release
        }
    }
}

 dependencies {
     implementation fileTree(include: ['*.jar'], dir: 'libs')
     implementation "androidx.localbroadcastmanager:localbroadcastmanager:1.0.0"
     implementation 'androidx.appcompat:appcompat:1.4.0'
     implementation 'androidx.preference:preference:1.1.1'
     implementation("com.squareup.okhttp3:okhttp:4.9.3")
 }