name: Android CI

on:
  push:
    tags:
     - 'v*'
  pull_request:
    tags:
     - 'v*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew assembleRelease
      
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false
        
    - name: Get Version Name
      uses: actions/github-script@v5.1.0
      id: get-version
      with:
        script: |
          const str=process.env.GITHUB_REF;
          return str.substring(str.indexOf("v"));
        result-encoding: string
        
    - name: Upload Release apk Asset
      id: upload-release-apk-asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
        asset_path: app/build/outputs/apk/release/app-release.apk # 上传路径
        asset_name: WeChatLuckyMoney-${{steps.get-version.outputs.result}}.apk # 资源名
        asset_content_type: application/vnd.android.package-archive #资源类型
        
    - name: Upload Release mapping Asset
      id: upload-release-mapping-asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
        asset_path: app/build/outputs/mapping/release/mapping.txt # 上传路径
        asset_name: mapping-${{steps.get-version.outputs.result}}.txt # 资源名
        asset_content_type: text/plain #资源类型

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.3.1
      with:
        path: app/build/outputs
